export const data = [
  {
    question: "What is the purpose of the useState hook in React?",
    option1: "To manage side effects",
    option2: "To add state to functional components",
    option3: "To interact with the DOM",
    option4: "To handle routing",
    ans: 2,
  },
  {
    question: "Which method is used to update state in a class component?",
    option1: "updateState()",
    option2: "setState()",
    option3: "changeState()",
    option4: "modifyState()",
    ans: 2,
  },
  {
    question: "What does JSX stand for?",
    option1: "JavaScript Syntax Extension",
    option2: "JavaScript XML",
    option3: "JavaScript XHTML",
    option4: "JavaScript and HTML",
    ans: 2,
  },
  {
    question: "Which hook is used to perform side effects in functional components?",
    option1: "useState",
    option2: "useEffect",
    option3: "useContext",
    option4: "useReducer",
    ans: 2,
  },
  {
    question: "What is the default port number in which the React application runs?",
    option1: "3000",
    option2: "5000",
    option3: "8000",
    option4: "8080",
    ans: 1,
  },
  {
    question: "How do you pass data from a parent component to a child component?",
    option1: "Using states",
    option2: "Using props",
    option3: "Using context",
    option4: "Using refs",
    ans: 2,
  },
  {
    question: "What is the virtual DOM in React?",
    option1: "A direct copy of the real DOM",
    option2: "An abstraction of the real DOM",
    option3: "A DOM that runs in a virtual machine",
    option4: "A DOM created for testing purposes",
    ans: 2,
  },
  {
    question: "Which of the following is true about React?",
    option1: "React is a framework",
    option2: "React is a library",
    option3: "React is a server-side language",
    option4: "React is a database",
    ans: 2,
  },
  {
    question: "What is the purpose of keys in React?",
    option1: "To uniquely identify elements in the DOM",
    option2: "To encrypt data",
    option3: "To handle user input",
    option4: "To manage state",
    ans: 1,
  },
  {
    question: "How can you optimize performance in a React application?",
    option1: "Using state for every variable",
    option2: "Avoiding use of hooks",
    option3: "Using keys to uniquely identify list items",
    option4: "Rendering everything on the server side",
    ans: 3,
  }
];